### PR TITLE
Remove all debug stuff from Travis build

### PR DESCRIPTION
**Pull request by andreasnoack**

### CODE REVIEW

**Comment by poulson** [comment]
It didn't go through :8ball:

**Comment by andreasnoack** [comment]
No that was why I asked about `ReadProxy.cpp`. I don't understand why `Elemental.jl` goes through but not this one. I don't see a big difference in the build setup.

**Comment by poulson** [comment]
Are both on the legacy infrastructure? Because the new infrastructure has more RAM.

**Comment by jakebolewski** [comment]
Pinging @tkelman as he is probably the one most familiar with the Travis infrastructure.  

The Elemental travis build keeps running out of memory but the Elemental.jl package (which clones and builds Elemental) does not.

**Comment by tkelman** [comment]
Try `sudo: false` for docker based 12.04 with a bit more memory, or
```
sudo: required
dist: trusty
```
for 14.04 with even more memory

**Comment by andreasnoack** [comment]
Okay. Now we try with "even more memory" so hopefully the build will make it though the proxy curse of dimensionality.

**Comment by tkelman** [comment]
You'll need to adjust the apt-get packages for 14.04.

**Comment by andreasnoack** [comment]
```
[ 38%] Building CXX object CMakeFiles/El.dir/src/core/ReadProxy.cpp.o
[ 39%] Building CXX object CMakeFiles/El.dir/src/core/Grid-C.cpp.o
```
I think this change was sufficient. Thanks @tkelman. There is some clang trusty stuff going wrong, but gcc will probably make it through.

**Comment by poulson** [comment]
@tkelman :100:

**Comment by jakebolewski** [comment]
:racehorse: :gun:

**Comment by poulson** [comment]
@jakebolewski Is the horse Travis or Elemental? :-(

**Comment by tkelman** [comment]
Looks like the failure was just a build time limit. Can you use binaries of more dependencies?

**Comment by poulson** [comment]
@tkelman If so, then it wouldn't really be a fair build test, as Elemental is often responsible for building ScaLAPACK.

**Comment by poulson** [comment]
My honest opinion is that the limitations on Travis make it *almost*, but not quite, suitable for use with Elemental.

**Comment by tkelman** [comment]
> Elemental is often responsible for building ScaLAPACK

Sure, but looks like more of the time is spent on openblas?

**Comment by andreasnoack** [comment]
@tkelman Is there only one core available on the `trusty` machines?

**Comment by tkelman** [comment]
should be 2 I think, there's a table somewhere (maybe travis ci's blog)

**Comment by poulson** [comment]
@tkelman Good point; I forgot about that. This typically only happens on Linux boxes.

**Pull request merged**
