### PR TITLE
Add Primefield

### PR DESCRIPTION
**Pull request by rhl-**
Issuing a preliminary pull request. I am wondering if travis will CI for me if I do this.

### CODE REVIEW

**Comment by poulson** [comment]
Hi Ryan,

It seem that there are several syntax errors in the test related to missing `typename` declarations.

**Comment by rhl-** [comment]
yeah, i believe they are fixed locally. I just wanted to see if this would work.

**Comment by poulson** [comment]
Ah, thanks for clarifying. In that case, I'll wait to review the changesets.

**Comment by rhl-** [comment]
@poulson, in your build system, it looks like you use file globs to build your tests. how do you make it recognize that a file has changed without deleting your build directory and starting from scratch?

**Comment by rhl-** [comment]
also, feel free to say anything if you see anything obvious.

**Comment by poulson** [comment]
@rhl- Touching the `CMakeLists.txt` and rerunning `make` refreshes the globbed list of files and picks up the build on the new executables (and does not require rebuilding the library or pre-existing executables).

**Comment by rhl-** [comment]
@poulson ok, I fixed the compiler errors, but, now I see that I need to export symbols for types like this:

    SparseMatrix< PrimeField< 3> > 

can you point out what I need to do to instantiate these sorts of templates?

**Comment by poulson** [comment]
If the number of types is to become unbounded, which, for practical purposes, it seems to be for your case, it only makes sense to move the `SparseMatrix` implementation entirely into the headers.

**Comment by rhl-** [comment]
@poulson wont this have dramatic effects on users? One could do the same thing for the dense matrix classes as well, and then all your matrix types are header only. I would imagine this would slow down compilation times dramatically. Perhaps an alternative is just exporting a small number of primes? Unless you don't mind moving to header only?

**Comment by poulson** [comment]
With a proper usage of explicit instantiations of common types and extern templates the compile times could perhaps even decrease. But this would need to happen at a library-wide level.

**Comment by rhl-** [comment]
I see. Perhaps we should tackle this first then.

**Pull request closed without merging**
