### PR TITLE
Fix ambiguous template special. errors with GCC 7+

### PR DESCRIPTION
**Pull request by JM1**
Fix for #254. See discussion in #254 in  #259.

### CODE REVIEW

**Comment by poulson** [comment]
LGTM. I will merge if/when the travis tests pass. Thanks!

**Comment by JM1** [comment]
Travis tests fail because Clang 6.0 crashs, fix for that will come later ( #263 ).

**Comment by poulson** [comment]
Which CL would you like me to review/merge first?

**Comment by JM1** [comment]
CL?

This PR (#264) first, then I'll open a new PR for another `.travis.yml` patch, which will allow Clang 6.0 to fail (my assumption for `allow_failures` is that Clang crashs because of an internal compiler bug).

**Comment by poulson** [comment]
Sorry, I meant Pull Request, not Change List. I have internalized company lingo apparently.

**Pull request merged**
