### PR TITLE
Add GCC 8 and Clang 6.0 to Travis CI.

### PR DESCRIPTION
**Pull request by JM1**
See discussion in #262

### CODE REVIEW

**Comment by JM1** [comment]
Travis CI build failure is expected due to #259

**Comment by poulson** [comment]
I am merging even though this will make the button on the homepage red. Thank you again!

**Comment by JM1** [comment]
Once #264 is accepted, I'll open a PR for [this commit](https://github.com/JM1/Elemental/compare/master...06ee95965d24) ([build logs](https://travis-ci.org/JM1/Elemental/builds/414148146)) which allows Clang 6.0 to fail.

**Comment by JM1** [comment]
..and then the button on the homepage will be green again.

**Pull request merged**
