### PR TITLE
WIP: Add MSVC CI builds

### PR DESCRIPTION
**Pull request by rhl-**
Try and get windows builds under CI. Even if they are failing its good to track progress.

### CODE REVIEW

**Comment by rhl-** [comment]
This addressed Issue #21

**Comment by rhl-** [comment]
This adds initial support for Windows CI. It is not working as it appears the subprojects PMRRR and METIS fail to build. I'm not sure why. Perhaps we can fix this up though.

**Comment by benderbuilder** [comment]
test this please

**Comment by benderbuilder** [comment]
test this please

**Comment by rhl-** [comment]
I've deleted the appveyor test as there is clearly a decent amount of work to be done to get it there. I'm going to commit appyevor.yml to master just so we have something to eventually pick up again.

**Pull request closed without merging**
